from flask import Flask, request, jsonify, send_from_directory, session, redirect, url_for
import google.generativeai as genai
import os

app = Flask(__name__)
app.secret_key = 'your-secret-key-here'  # Replace with a secure key

# Gemini API key
API_KEY = 'AIzaSyDrvhhdVqCtfvYZTFOJoiokvwTGO3PPTOM'
genai.configure(api_key=API_KEY)

# Hardcoded credentials
USERS = {
    "admin": "password123",
    "user": "factspark"
}

@app.route('/login', methods=['GET'])
def login_page():
    if 'logged_in' in session:
        return redirect(url_for('serve_html'))
    return send_from_directory('static', 'login.html')

@app.route('/login', methods=['POST'])
def login():
    data = request.get_json()
    print("Received data:", data)  # Debug
    username = data.get('username')
    password = data.get('password')
    print("Username:", username, "Password:", password)  # Debug

    if username in USERS and USERS[username] == password:
        session['logged_in'] = True
        print("Login successful for:", username)
        return jsonify({"status": "success"})
    else:
        print("Login failed for:", username)
        return jsonify({"status": "error", "error": "Invalid username or password"}), 401

@app.route('/')
def serve_html():
    if 'logged_in' not in session:
        return redirect(url_for('login_page'))
    return send_from_directory('static', 'index.html')

@app.route('/generate-facts', methods=['POST'])
def generate_facts():
    if 'logged_in' not in session:
        return jsonify({"error": "Please log in to generate facts"}), 403
    try:
        data = request.get_json()
        context = data.get('context', '').strip()
        language = data.get('language', 'English')
        options = int(data.get('options', 5))

        if options <= 0 or options > 10:
            return jsonify({"error": "Number of options must be between 1 and 10"}), 400

        # Updated language validation
        if language not in ['English', 'Telugu', 'Hindi']:
            return jsonify({"error": "Language not supported. Choose from English, Telugu, or Hindi."}), 400

        # Updated language prompts
        lang_prompt = {
            "English": "in English",
            "Telugu": "తెలుగులో",  # "in Telugu"
            "Hindi": "हिन्दी में"   # "in Hindi"
        }[language]
        prompt = f"Generate {options} interesting facts about {context} {lang_prompt}." if context else f"Generate {options} random interesting facts {lang_prompt}."

        model = genai.GenerativeModel('gemini-1.5-flash')
        response = model.generate_content(prompt)

        if not response.text:
            return jsonify({"error": "No facts generated by the API"}), 500

        facts = response.text.strip().split('\n')
        cleaned_facts = [fact.lstrip('1234567890. ').strip() for fact in facts if fact.strip()]
        selected_facts = cleaned_facts[:min(options, len(cleaned_facts))]

        if not selected_facts:
            return jsonify({"error": "Failed to generate valid facts"}), 500

        return jsonify({"status": "success", "facts": selected_facts, "count": len(selected_facts)})

    except ValueError:
        return jsonify({"error": "Invalid number of options provided"}), 400
    except Exception as e:
        return jsonify({"error": f"An error occurred: {str(e)}"}), 500

@app.route('/logout')
def logout():
    session.pop('logged_in', None)
    return redirect(url_for('login_page'))

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
